CREATE DATABASE readinglist;

CREATE TABLE "user" (
    user_id SERIAL PRIMARY KEY,
    username VARCHAR(30) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, --NEED TO DO THIS BECAUSE I HAVE NOT YET
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);